<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>44.9. PL/Tclにおける明示的サブトランザクション</title><link rel="stylesheet" type="text/css" href="stylesheet.css" /><link rev="made" href="pgsql-docs@lists.postgresql.org" /><meta name="generator" content="DocBook XSL Stylesheets V1.79.1" /><link rel="prev" href="pltcl-error-handling.html" title="44.8. PL/Tclのエラー処理" /><link rel="next" href="pltcl-transactions.html" title="44.10. トランザクション制御" /><meta name="viewport" content="width=device-width,initial-scale=1.0" /></head><body><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="4" align="center"><a accesskey="h" href="index.html">PostgreSQL 11.4文書</a></th></tr><tr><td width="10%" align="left"></td><td width="10%" align="left"></td><td width="60%" align="center"><a href="pltcl.html" title="第44章 PL/Tcl - Tcl手続き言語">第44章 PL/Tcl - Tcl手続き言語</a></td><td width="20%" align="right"></td></tr><tr><td width="10%" align="left"><a accesskey="p" href="pltcl-error-handling.html" title="44.8. PL/Tclのエラー処理">前へ</a> </td><td width="10%" align="left"><a accesskey="u" href="pltcl.html" title="第44章 PL/Tcl - Tcl手続き言語">上へ</a></td><td width="60%" align="center">44.9. PL/Tclにおける明示的サブトランザクション</td><td width="20%" align="right"> <a accesskey="n" href="pltcl-transactions.html" title="44.10. トランザクション制御">次へ</a></td></tr></table><hr /></div><div class="sect1" id="PLTCL-SUBTRANSACTIONS"><div class="titlepage"><div><div><h2 class="title" style="clear: both">44.9. PL/Tclにおける明示的サブトランザクション</h2></div></div></div><!--
    <title>Explicit Subtransactions in PL/Tcl</title>
--><a id="id-1.8.9.13.2" class="indexterm"></a><p>
<!--
     Recovering from errors caused by database access as described in
     <xref linkend="pltcl-error-handling"/> can lead to an undesirable
     situation where some operations succeed before one of them fails,
     and after recovering from that error the data is left in an
     inconsistent state.  PL/Tcl offers a solution to this problem in
     the form of explicit subtransactions.
-->
<a class="xref" href="pltcl-error-handling.html" title="44.8. PL/Tclのエラー処理">44.8</a>で説明されているように、データベースアクセスによって生じたエラーからの回復により、操作のうちいくつかが失敗する前に他の操作が成功し、エラーからの回復後、データの一貫性が失われた望ましくない状態になってしまう可能性があります。
PL/Tclは明示的なトランザクションの手法でこの問題を解決する手段を提供しています。
    </p><p>
<!--
     Consider a function that implements a transfer between two accounts:
-->
2つのアカウントの間の送金を実装する関数を考えます。
</p><pre class="programlisting">
CREATE FUNCTION transfer_funds() RETURNS void AS $$
    if [catch {
        spi_exec "UPDATE accounts SET balance = balance - 100 WHERE account_name = 'joe'"
        spi_exec "UPDATE accounts SET balance = balance + 100 WHERE account_name = 'mary'"
    } errormsg] {
        set result [format "error transferring funds: %s" $errormsg]
    } else {
        set result "funds transferred successfully"
    }
    spi_exec "INSERT INTO operations (result) VALUES ('[quote $result]')"
$$ LANGUAGE pltcl;
</pre><p>
<!--
     If the second <command>UPDATE</command> statement results in an
     exception being raised, this function will log the failure, but
     the result of the first <command>UPDATE</command> will
     nevertheless be committed.  In other words, the funds will be
     withdrawn from Joe's account, but will not be transferred to
     Mary's account.  This happens because each <function>spi_exec</function>
     is a separate subtransaction, and only one of those subtransactions
     got rolled back.
-->
ふたつ目の<code class="command">UPDATE</code>文で例外が発生する結果になると、この関数は失敗を記録しますが、それにもかかわらず、最初の<code class="command">UPDATE</code>はコミットされます。
言い換えると、Joeのアカウントから資金が引き出されたのに、Maryのアカウントには転送されません。
これは、それぞれの<code class="function">spi_exec</code>が別々のサブトランザクションになっていて、そのうち一つのサブトランザクションだけがロールバックされるからです。
    </p><p>
<!--
     To handle such cases, you can wrap multiple database operations in an
     explicit subtransaction, which will succeed or roll back as a whole.
     PL/Tcl provides a <function>subtransaction</function> command to manage
     this.  We can rewrite our function as:
-->
このような状況に対応するには、複数のデータベース操作を、全体が成功するか、あるいは失敗する明示的なサブトランザクションで包みます。
PL/Tclは、これを管理するための<code class="function">subtransaction</code>コマンドを提供しています。
</p><pre class="programlisting">
CREATE FUNCTION transfer_funds2() RETURNS void AS $$
    if [catch {
        subtransaction {
            spi_exec "UPDATE accounts SET balance = balance - 100 WHERE account_name = 'joe'"
            spi_exec "UPDATE accounts SET balance = balance + 100 WHERE account_name = 'mary'"
        }
    } errormsg] {
        set result [format "error transferring funds: %s" $errormsg]
    } else {
        set result "funds transferred successfully"
    }
    spi_exec "INSERT INTO operations (result) VALUES ('[quote $result]')"
$$ LANGUAGE pltcl;
</pre><p>
<!--
     Note that use of <function>catch</function> is still required for this
     purpose.  Otherwise the error would propagate to the top level of the
     function, preventing the desired insertion into
     the <structname>operations</structname> table.
     The <function>subtransaction</function> command does not trap errors, it
     only assures that all database operations executed inside its scope will
     be rolled back together when an error is reported.
-->
この目的のために、<code class="function">catch</code>が必要であることに注意してください。
そうでないと、エラーが関数のトップレベルまで伝搬し、期待したような<code class="structname">operations</code>テーブルへの挿入が阻害されてしまいます。
<code class="function">subtransaction</code>コマンドはエラーを補足しません。
エラーが報告された際に、スコープの内側で実行されたすべてのデータベース操作がロールバックされることを保証するだけです。
    </p><p>
<!--
     A rollback of an explicit subtransaction occurs on any error reported
     by the contained Tcl code, not only errors originating from database
     access.  Thus a regular Tcl exception raised inside
     a <function>subtransaction</function> command will also cause the
     subtransaction to be rolled back.  However, non-error exits out of the
     contained Tcl code (for instance, due to <function>return</function>) do
     not cause a rollback.
-->
明示的なサブトランザクションのロールバックは、Tclのコードの中でエラーが報告された際だけでなく、データベースアクセスに起因するエラーの際にも起こります。
ですから、<code class="function">subtransaction</code>コマンド内の内側で起こった通常のTcl例外は、サブトランザクションのロールバックも引き起こします。
しかし、Tclコードからのエラーによらない脱出（たとえば<code class="function">return</code>によるもの）は、ロールバックをもたらしません。
    </p></div><div class="navfooter"><hr /><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="pltcl-error-handling.html">前へ</a> </td><td width="20%" align="center"><a accesskey="u" href="pltcl.html">上へ</a></td><td width="40%" align="right"> <a accesskey="n" href="pltcl-transactions.html">次へ</a></td></tr><tr><td width="40%" align="left" valign="top">44.8. PL/Tclのエラー処理 </td><td width="20%" align="center"><a accesskey="h" href="index.html">ホーム</a></td><td width="40%" align="right" valign="top"> 44.10. トランザクション制御</td></tr></table></div></body></html>